### PR TITLE
Improve repository names for weekly generator

### PR DESCRIPTION
**Pull request by kpodemski**

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
CI failed. Relaunching as it was just for python3.7

**Comment by matks** [comment]
@kpodemski Are you a skilled python developer? 😅

**Comment by kpodemski** [comment]
@matks well, unfortunately, I'm not :D It looks like something is wrong with the dependency itself

maybe it's a chance to redo this script in PHP because we are going to change `Core weekly` to `Core monthly` :)

**Comment by matks** [comment]
> @matks well, unfortunately, I'm not :D It looks like something is wrong with the dependency itself
> 
> maybe it's a chance to redo this script in PHP because we are going to change `Core weekly` to `Core monthly` :)

Most of this tool logic is calling the right GitHub URL and parsing/grouping the data returned. It should be OK to do in PHP 👍

**Comment by matks** [comment]
Merged using GitHub admin rights as CI fail is wrong

**Pull request merged**
